/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as SitemapDotxmlRouteImport } from './routes/sitemap[.]xml'
import { Route as CalculatorRouteImport } from './routes/calculator'
import { Route as AuthRouteImport } from './routes/auth'
import { Route as ApiDocsRouteImport } from './routes/api-docs'
import { Route as AuthenticatedRouteRouteImport } from './routes/_authenticated/route'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AuthenticatedPayrollRouteImport } from './routes/_authenticated/payroll'
import { Route as AuthenticatedEmployeesRouteImport } from './routes/_authenticated/employees'
import { Route as AuthenticatedDashboardRouteImport } from './routes/_authenticated/dashboard'
import { Route as AuthenticatedCountryPacksRouteImport } from './routes/_authenticated/country-packs'
import { Route as AuthenticatedContractsRouteImport } from './routes/_authenticated/contracts'
import { Route as AuthenticatedCalendarRouteImport } from './routes/_authenticated/calendar'
import { Route as AuthenticatedAuditRouteImport } from './routes/_authenticated/audit'
import { Route as ApiPublicOpenapiDotjsonRouteImport } from './routes/api/public/openapi[.]json'
import { Route as ApiPublicCalculateTaxRouteImport } from './routes/api/public/calculate-tax'
import { Route as ApiPublicCalculateBpjsRouteImport } from './routes/api/public/calculate-bpjs'
import { Route as ApiPublicV1OpenapiDotjsonRouteImport } from './routes/api/public/v1/openapi[.]json'
import { Route as ApiPublicV1HealthRouteImport } from './routes/api/public/v1/health'
import { Route as ApiPublicV1CalculateTaxRouteImport } from './routes/api/public/v1/calculate-tax'
import { Route as ApiPublicV1CalculateBpjsRouteImport } from './routes/api/public/v1/calculate-bpjs'

const SitemapDotxmlRoute = SitemapDotxmlRouteImport.update({
  id: '/sitemap.xml',
  path: '/sitemap.xml',
  getParentRoute: () => rootRouteImport,
} as any)
const CalculatorRoute = CalculatorRouteImport.update({
  id: '/calculator',
  path: '/calculator',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthRoute = AuthRouteImport.update({
  id: '/auth',
  path: '/auth',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiDocsRoute = ApiDocsRouteImport.update({
  id: '/api-docs',
  path: '/api-docs',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedRouteRoute = AuthenticatedRouteRouteImport.update({
  id: '/_authenticated',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedPayrollRoute = AuthenticatedPayrollRouteImport.update({
  id: '/payroll',
  path: '/payroll',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedEmployeesRoute = AuthenticatedEmployeesRouteImport.update({
  id: '/employees',
  path: '/employees',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedDashboardRoute = AuthenticatedDashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedCountryPacksRoute =
  AuthenticatedCountryPacksRouteImport.update({
    id: '/country-packs',
    path: '/country-packs',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedContractsRoute = AuthenticatedContractsRouteImport.update({
  id: '/contracts',
  path: '/contracts',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedCalendarRoute = AuthenticatedCalendarRouteImport.update({
  id: '/calendar',
  path: '/calendar',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedAuditRoute = AuthenticatedAuditRouteImport.update({
  id: '/audit',
  path: '/audit',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const ApiPublicOpenapiDotjsonRoute = ApiPublicOpenapiDotjsonRouteImport.update({
  id: '/api/public/openapi.json',
  path: '/api/public/openapi.json',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiPublicCalculateTaxRoute = ApiPublicCalculateTaxRouteImport.update({
  id: '/api/public/calculate-tax',
  path: '/api/public/calculate-tax',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiPublicCalculateBpjsRoute = ApiPublicCalculateBpjsRouteImport.update({
  id: '/api/public/calculate-bpjs',
  path: '/api/public/calculate-bpjs',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiPublicV1OpenapiDotjsonRoute =
  ApiPublicV1OpenapiDotjsonRouteImport.update({
    id: '/api/public/v1/openapi.json',
    path: '/api/public/v1/openapi.json',
    getParentRoute: () => rootRouteImport,
  } as any)
const ApiPublicV1HealthRoute = ApiPublicV1HealthRouteImport.update({
  id: '/api/public/v1/health',
  path: '/api/public/v1/health',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiPublicV1CalculateTaxRoute = ApiPublicV1CalculateTaxRouteImport.update({
  id: '/api/public/v1/calculate-tax',
  path: '/api/public/v1/calculate-tax',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiPublicV1CalculateBpjsRoute =
  ApiPublicV1CalculateBpjsRouteImport.update({
    id: '/api/public/v1/calculate-bpjs',
    path: '/api/public/v1/calculate-bpjs',
    getParentRoute: () => rootRouteImport,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/api-docs': typeof ApiDocsRoute
  '/auth': typeof AuthRoute
  '/calculator': typeof CalculatorRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/audit': typeof AuthenticatedAuditRoute
  '/calendar': typeof AuthenticatedCalendarRoute
  '/contracts': typeof AuthenticatedContractsRoute
  '/country-packs': typeof AuthenticatedCountryPacksRoute
  '/dashboard': typeof AuthenticatedDashboardRoute
  '/employees': typeof AuthenticatedEmployeesRoute
  '/payroll': typeof AuthenticatedPayrollRoute
  '/api/public/calculate-bpjs': typeof ApiPublicCalculateBpjsRoute
  '/api/public/calculate-tax': typeof ApiPublicCalculateTaxRoute
  '/api/public/openapi.json': typeof ApiPublicOpenapiDotjsonRoute
  '/api/public/v1/calculate-bpjs': typeof ApiPublicV1CalculateBpjsRoute
  '/api/public/v1/calculate-tax': typeof ApiPublicV1CalculateTaxRoute
  '/api/public/v1/health': typeof ApiPublicV1HealthRoute
  '/api/public/v1/openapi.json': typeof ApiPublicV1OpenapiDotjsonRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/api-docs': typeof ApiDocsRoute
  '/auth': typeof AuthRoute
  '/calculator': typeof CalculatorRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/audit': typeof AuthenticatedAuditRoute
  '/calendar': typeof AuthenticatedCalendarRoute
  '/contracts': typeof AuthenticatedContractsRoute
  '/country-packs': typeof AuthenticatedCountryPacksRoute
  '/dashboard': typeof AuthenticatedDashboardRoute
  '/employees': typeof AuthenticatedEmployeesRoute
  '/payroll': typeof AuthenticatedPayrollRoute
  '/api/public/calculate-bpjs': typeof ApiPublicCalculateBpjsRoute
  '/api/public/calculate-tax': typeof ApiPublicCalculateTaxRoute
  '/api/public/openapi.json': typeof ApiPublicOpenapiDotjsonRoute
  '/api/public/v1/calculate-bpjs': typeof ApiPublicV1CalculateBpjsRoute
  '/api/public/v1/calculate-tax': typeof ApiPublicV1CalculateTaxRoute
  '/api/public/v1/health': typeof ApiPublicV1HealthRoute
  '/api/public/v1/openapi.json': typeof ApiPublicV1OpenapiDotjsonRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_authenticated': typeof AuthenticatedRouteRouteWithChildren
  '/api-docs': typeof ApiDocsRoute
  '/auth': typeof AuthRoute
  '/calculator': typeof CalculatorRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/_authenticated/audit': typeof AuthenticatedAuditRoute
  '/_authenticated/calendar': typeof AuthenticatedCalendarRoute
  '/_authenticated/contracts': typeof AuthenticatedContractsRoute
  '/_authenticated/country-packs': typeof AuthenticatedCountryPacksRoute
  '/_authenticated/dashboard': typeof AuthenticatedDashboardRoute
  '/_authenticated/employees': typeof AuthenticatedEmployeesRoute
  '/_authenticated/payroll': typeof AuthenticatedPayrollRoute
  '/api/public/calculate-bpjs': typeof ApiPublicCalculateBpjsRoute
  '/api/public/calculate-tax': typeof ApiPublicCalculateTaxRoute
  '/api/public/openapi.json': typeof ApiPublicOpenapiDotjsonRoute
  '/api/public/v1/calculate-bpjs': typeof ApiPublicV1CalculateBpjsRoute
  '/api/public/v1/calculate-tax': typeof ApiPublicV1CalculateTaxRoute
  '/api/public/v1/health': typeof ApiPublicV1HealthRoute
  '/api/public/v1/openapi.json': typeof ApiPublicV1OpenapiDotjsonRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/api-docs'
    | '/auth'
    | '/calculator'
    | '/sitemap.xml'
    | '/audit'
    | '/calendar'
    | '/contracts'
    | '/country-packs'
    | '/dashboard'
    | '/employees'
    | '/payroll'
    | '/api/public/calculate-bpjs'
    | '/api/public/calculate-tax'
    | '/api/public/openapi.json'
    | '/api/public/v1/calculate-bpjs'
    | '/api/public/v1/calculate-tax'
    | '/api/public/v1/health'
    | '/api/public/v1/openapi.json'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/api-docs'
    | '/auth'
    | '/calculator'
    | '/sitemap.xml'
    | '/audit'
    | '/calendar'
    | '/contracts'
    | '/country-packs'
    | '/dashboard'
    | '/employees'
    | '/payroll'
    | '/api/public/calculate-bpjs'
    | '/api/public/calculate-tax'
    | '/api/public/openapi.json'
    | '/api/public/v1/calculate-bpjs'
    | '/api/public/v1/calculate-tax'
    | '/api/public/v1/health'
    | '/api/public/v1/openapi.json'
  id:
    | '__root__'
    | '/'
    | '/_authenticated'
    | '/api-docs'
    | '/auth'
    | '/calculator'
    | '/sitemap.xml'
    | '/_authenticated/audit'
    | '/_authenticated/calendar'
    | '/_authenticated/contracts'
    | '/_authenticated/country-packs'
    | '/_authenticated/dashboard'
    | '/_authenticated/employees'
    | '/_authenticated/payroll'
    | '/api/public/calculate-bpjs'
    | '/api/public/calculate-tax'
    | '/api/public/openapi.json'
    | '/api/public/v1/calculate-bpjs'
    | '/api/public/v1/calculate-tax'
    | '/api/public/v1/health'
    | '/api/public/v1/openapi.json'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AuthenticatedRouteRoute: typeof AuthenticatedRouteRouteWithChildren
  ApiDocsRoute: typeof ApiDocsRoute
  AuthRoute: typeof AuthRoute
  CalculatorRoute: typeof CalculatorRoute
  SitemapDotxmlRoute: typeof SitemapDotxmlRoute
  ApiPublicCalculateBpjsRoute: typeof ApiPublicCalculateBpjsRoute
  ApiPublicCalculateTaxRoute: typeof ApiPublicCalculateTaxRoute
  ApiPublicOpenapiDotjsonRoute: typeof ApiPublicOpenapiDotjsonRoute
  ApiPublicV1CalculateBpjsRoute: typeof ApiPublicV1CalculateBpjsRoute
  ApiPublicV1CalculateTaxRoute: typeof ApiPublicV1CalculateTaxRoute
  ApiPublicV1HealthRoute: typeof ApiPublicV1HealthRoute
  ApiPublicV1OpenapiDotjsonRoute: typeof ApiPublicV1OpenapiDotjsonRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/sitemap.xml': {
      id: '/sitemap.xml'
      path: '/sitemap.xml'
      fullPath: '/sitemap.xml'
      preLoaderRoute: typeof SitemapDotxmlRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/calculator': {
      id: '/calculator'
      path: '/calculator'
      fullPath: '/calculator'
      preLoaderRoute: typeof CalculatorRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth': {
      id: '/auth'
      path: '/auth'
      fullPath: '/auth'
      preLoaderRoute: typeof AuthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api-docs': {
      id: '/api-docs'
      path: '/api-docs'
      fullPath: '/api-docs'
      preLoaderRoute: typeof ApiDocsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated': {
      id: '/_authenticated'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AuthenticatedRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/payroll': {
      id: '/_authenticated/payroll'
      path: '/payroll'
      fullPath: '/payroll'
      preLoaderRoute: typeof AuthenticatedPayrollRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/employees': {
      id: '/_authenticated/employees'
      path: '/employees'
      fullPath: '/employees'
      preLoaderRoute: typeof AuthenticatedEmployeesRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/dashboard': {
      id: '/_authenticated/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof AuthenticatedDashboardRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/country-packs': {
      id: '/_authenticated/country-packs'
      path: '/country-packs'
      fullPath: '/country-packs'
      preLoaderRoute: typeof AuthenticatedCountryPacksRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/contracts': {
      id: '/_authenticated/contracts'
      path: '/contracts'
      fullPath: '/contracts'
      preLoaderRoute: typeof AuthenticatedContractsRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/calendar': {
      id: '/_authenticated/calendar'
      path: '/calendar'
      fullPath: '/calendar'
      preLoaderRoute: typeof AuthenticatedCalendarRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/audit': {
      id: '/_authenticated/audit'
      path: '/audit'
      fullPath: '/audit'
      preLoaderRoute: typeof AuthenticatedAuditRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/api/public/openapi.json': {
      id: '/api/public/openapi.json'
      path: '/api/public/openapi.json'
      fullPath: '/api/public/openapi.json'
      preLoaderRoute: typeof ApiPublicOpenapiDotjsonRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/calculate-tax': {
      id: '/api/public/calculate-tax'
      path: '/api/public/calculate-tax'
      fullPath: '/api/public/calculate-tax'
      preLoaderRoute: typeof ApiPublicCalculateTaxRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/calculate-bpjs': {
      id: '/api/public/calculate-bpjs'
      path: '/api/public/calculate-bpjs'
      fullPath: '/api/public/calculate-bpjs'
      preLoaderRoute: typeof ApiPublicCalculateBpjsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/v1/openapi.json': {
      id: '/api/public/v1/openapi.json'
      path: '/api/public/v1/openapi.json'
      fullPath: '/api/public/v1/openapi.json'
      preLoaderRoute: typeof ApiPublicV1OpenapiDotjsonRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/v1/health': {
      id: '/api/public/v1/health'
      path: '/api/public/v1/health'
      fullPath: '/api/public/v1/health'
      preLoaderRoute: typeof ApiPublicV1HealthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/v1/calculate-tax': {
      id: '/api/public/v1/calculate-tax'
      path: '/api/public/v1/calculate-tax'
      fullPath: '/api/public/v1/calculate-tax'
      preLoaderRoute: typeof ApiPublicV1CalculateTaxRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/v1/calculate-bpjs': {
      id: '/api/public/v1/calculate-bpjs'
      path: '/api/public/v1/calculate-bpjs'
      fullPath: '/api/public/v1/calculate-bpjs'
      preLoaderRoute: typeof ApiPublicV1CalculateBpjsRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

interface AuthenticatedRouteRouteChildren {
  AuthenticatedAuditRoute: typeof AuthenticatedAuditRoute
  AuthenticatedCalendarRoute: typeof AuthenticatedCalendarRoute
  AuthenticatedContractsRoute: typeof AuthenticatedContractsRoute
  AuthenticatedCountryPacksRoute: typeof AuthenticatedCountryPacksRoute
  AuthenticatedDashboardRoute: typeof AuthenticatedDashboardRoute
  AuthenticatedEmployeesRoute: typeof AuthenticatedEmployeesRoute
  AuthenticatedPayrollRoute: typeof AuthenticatedPayrollRoute
}

const AuthenticatedRouteRouteChildren: AuthenticatedRouteRouteChildren = {
  AuthenticatedAuditRoute: AuthenticatedAuditRoute,
  AuthenticatedCalendarRoute: AuthenticatedCalendarRoute,
  AuthenticatedContractsRoute: AuthenticatedContractsRoute,
  AuthenticatedCountryPacksRoute: AuthenticatedCountryPacksRoute,
  AuthenticatedDashboardRoute: AuthenticatedDashboardRoute,
  AuthenticatedEmployeesRoute: AuthenticatedEmployeesRoute,
  AuthenticatedPayrollRoute: AuthenticatedPayrollRoute,
}

const AuthenticatedRouteRouteWithChildren =
  AuthenticatedRouteRoute._addFileChildren(AuthenticatedRouteRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AuthenticatedRouteRoute: AuthenticatedRouteRouteWithChildren,
  ApiDocsRoute: ApiDocsRoute,
  AuthRoute: AuthRoute,
  CalculatorRoute: CalculatorRoute,
  SitemapDotxmlRoute: SitemapDotxmlRoute,
  ApiPublicCalculateBpjsRoute: ApiPublicCalculateBpjsRoute,
  ApiPublicCalculateTaxRoute: ApiPublicCalculateTaxRoute,
  ApiPublicOpenapiDotjsonRoute: ApiPublicOpenapiDotjsonRoute,
  ApiPublicV1CalculateBpjsRoute: ApiPublicV1CalculateBpjsRoute,
  ApiPublicV1CalculateTaxRoute: ApiPublicV1CalculateTaxRoute,
  ApiPublicV1HealthRoute: ApiPublicV1HealthRoute,
  ApiPublicV1OpenapiDotjsonRoute: ApiPublicV1OpenapiDotjsonRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
