/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as SitemapDotxmlRouteImport } from './routes/sitemap[.]xml'
import { Route as CalculatorRouteImport } from './routes/calculator'
import { Route as AuthRouteImport } from './routes/auth'
import { Route as ApiDocsRouteImport } from './routes/api-docs'
import { Route as PlatformRouteRouteImport } from './routes/platform/route'
import { Route as AuthenticatedRouteRouteImport } from './routes/_authenticated/route'
import { Route as IndexRouteImport } from './routes/index'
import { Route as PlatformIndexRouteImport } from './routes/platform/index'
import { Route as PacksIndexRouteImport } from './routes/packs.index'
import { Route as PlatformUadaRouteImport } from './routes/platform/uada'
import { Route as PlatformReleasesRouteImport } from './routes/platform/releases'
import { Route as PlatformReadinessRouteImport } from './routes/platform/readiness'
import { Route as PlatformParametersRouteImport } from './routes/platform/parameters'
import { Route as PlatformPacksRouteImport } from './routes/platform/packs'
import { Route as PlatformFlagsRouteImport } from './routes/platform/flags'
import { Route as PlatformAuditRouteImport } from './routes/platform/audit'
import { Route as AuthenticatedPayrollRouteImport } from './routes/_authenticated/payroll'
import { Route as AuthenticatedEmployeesRouteImport } from './routes/_authenticated/employees'
import { Route as AuthenticatedDashboardRouteImport } from './routes/_authenticated/dashboard'
import { Route as AuthenticatedCountryPacksRouteImport } from './routes/_authenticated/country-packs'
import { Route as AuthenticatedContractsRouteImport } from './routes/_authenticated/contracts'
import { Route as AuthenticatedCalendarRouteImport } from './routes/_authenticated/calendar'
import { Route as AuthenticatedAuditRouteImport } from './routes/_authenticated/audit'
import { Route as ApiPublicOpenapiDotjsonRouteImport } from './routes/api/public/openapi[.]json'
import { Route as ApiPublicCalculateTaxRouteImport } from './routes/api/public/calculate-tax'
import { Route as ApiPublicCalculateBpjsRouteImport } from './routes/api/public/calculate-bpjs'
import { Route as ApiPublicV1ReadinessRouteImport } from './routes/api/public/v1/readiness'
import { Route as ApiPublicV1OpenapiDotjsonRouteImport } from './routes/api/public/v1/openapi[.]json'
import { Route as ApiPublicV1HealthRouteImport } from './routes/api/public/v1/health'
import { Route as ApiPublicV1CalculateTaxRouteImport } from './routes/api/public/v1/calculate-tax'
import { Route as ApiPublicV1CalculateBpjsRouteImport } from './routes/api/public/v1/calculate-bpjs'

const SitemapDotxmlRoute = SitemapDotxmlRouteImport.update({
  id: '/sitemap.xml',
  path: '/sitemap.xml',
  getParentRoute: () => rootRouteImport,
} as any)
const CalculatorRoute = CalculatorRouteImport.update({
  id: '/calculator',
  path: '/calculator',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthRoute = AuthRouteImport.update({
  id: '/auth',
  path: '/auth',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiDocsRoute = ApiDocsRouteImport.update({
  id: '/api-docs',
  path: '/api-docs',
  getParentRoute: () => rootRouteImport,
} as any)
const PlatformRouteRoute = PlatformRouteRouteImport.update({
  id: '/platform',
  path: '/platform',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedRouteRoute = AuthenticatedRouteRouteImport.update({
  id: '/_authenticated',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const PlatformIndexRoute = PlatformIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => PlatformRouteRoute,
} as any)
const PacksIndexRoute = PacksIndexRouteImport.update({
  id: '/packs/',
  path: '/packs/',
  getParentRoute: () => rootRouteImport,
} as any)
const PlatformUadaRoute = PlatformUadaRouteImport.update({
  id: '/uada',
  path: '/uada',
  getParentRoute: () => PlatformRouteRoute,
} as any)
const PlatformReleasesRoute = PlatformReleasesRouteImport.update({
  id: '/releases',
  path: '/releases',
  getParentRoute: () => PlatformRouteRoute,
} as any)
const PlatformReadinessRoute = PlatformReadinessRouteImport.update({
  id: '/readiness',
  path: '/readiness',
  getParentRoute: () => PlatformRouteRoute,
} as any)
const PlatformParametersRoute = PlatformParametersRouteImport.update({
  id: '/parameters',
  path: '/parameters',
  getParentRoute: () => PlatformRouteRoute,
} as any)
const PlatformPacksRoute = PlatformPacksRouteImport.update({
  id: '/packs',
  path: '/packs',
  getParentRoute: () => PlatformRouteRoute,
} as any)
const PlatformFlagsRoute = PlatformFlagsRouteImport.update({
  id: '/flags',
  path: '/flags',
  getParentRoute: () => PlatformRouteRoute,
} as any)
const PlatformAuditRoute = PlatformAuditRouteImport.update({
  id: '/audit',
  path: '/audit',
  getParentRoute: () => PlatformRouteRoute,
} as any)
const AuthenticatedPayrollRoute = AuthenticatedPayrollRouteImport.update({
  id: '/payroll',
  path: '/payroll',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedEmployeesRoute = AuthenticatedEmployeesRouteImport.update({
  id: '/employees',
  path: '/employees',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedDashboardRoute = AuthenticatedDashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedCountryPacksRoute =
  AuthenticatedCountryPacksRouteImport.update({
    id: '/country-packs',
    path: '/country-packs',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedContractsRoute = AuthenticatedContractsRouteImport.update({
  id: '/contracts',
  path: '/contracts',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedCalendarRoute = AuthenticatedCalendarRouteImport.update({
  id: '/calendar',
  path: '/calendar',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedAuditRoute = AuthenticatedAuditRouteImport.update({
  id: '/audit',
  path: '/audit',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const ApiPublicOpenapiDotjsonRoute = ApiPublicOpenapiDotjsonRouteImport.update({
  id: '/api/public/openapi.json',
  path: '/api/public/openapi.json',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiPublicCalculateTaxRoute = ApiPublicCalculateTaxRouteImport.update({
  id: '/api/public/calculate-tax',
  path: '/api/public/calculate-tax',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiPublicCalculateBpjsRoute = ApiPublicCalculateBpjsRouteImport.update({
  id: '/api/public/calculate-bpjs',
  path: '/api/public/calculate-bpjs',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiPublicV1ReadinessRoute = ApiPublicV1ReadinessRouteImport.update({
  id: '/api/public/v1/readiness',
  path: '/api/public/v1/readiness',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiPublicV1OpenapiDotjsonRoute =
  ApiPublicV1OpenapiDotjsonRouteImport.update({
    id: '/api/public/v1/openapi.json',
    path: '/api/public/v1/openapi.json',
    getParentRoute: () => rootRouteImport,
  } as any)
const ApiPublicV1HealthRoute = ApiPublicV1HealthRouteImport.update({
  id: '/api/public/v1/health',
  path: '/api/public/v1/health',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiPublicV1CalculateTaxRoute = ApiPublicV1CalculateTaxRouteImport.update({
  id: '/api/public/v1/calculate-tax',
  path: '/api/public/v1/calculate-tax',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiPublicV1CalculateBpjsRoute =
  ApiPublicV1CalculateBpjsRouteImport.update({
    id: '/api/public/v1/calculate-bpjs',
    path: '/api/public/v1/calculate-bpjs',
    getParentRoute: () => rootRouteImport,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/platform': typeof PlatformRouteRouteWithChildren
  '/api-docs': typeof ApiDocsRoute
  '/auth': typeof AuthRoute
  '/calculator': typeof CalculatorRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/audit': typeof AuthenticatedAuditRoute
  '/calendar': typeof AuthenticatedCalendarRoute
  '/contracts': typeof AuthenticatedContractsRoute
  '/country-packs': typeof AuthenticatedCountryPacksRoute
  '/dashboard': typeof AuthenticatedDashboardRoute
  '/employees': typeof AuthenticatedEmployeesRoute
  '/payroll': typeof AuthenticatedPayrollRoute
  '/platform/audit': typeof PlatformAuditRoute
  '/platform/flags': typeof PlatformFlagsRoute
  '/platform/packs': typeof PlatformPacksRoute
  '/platform/parameters': typeof PlatformParametersRoute
  '/platform/readiness': typeof PlatformReadinessRoute
  '/platform/releases': typeof PlatformReleasesRoute
  '/platform/uada': typeof PlatformUadaRoute
  '/packs/': typeof PacksIndexRoute
  '/platform/': typeof PlatformIndexRoute
  '/api/public/calculate-bpjs': typeof ApiPublicCalculateBpjsRoute
  '/api/public/calculate-tax': typeof ApiPublicCalculateTaxRoute
  '/api/public/openapi.json': typeof ApiPublicOpenapiDotjsonRoute
  '/api/public/v1/calculate-bpjs': typeof ApiPublicV1CalculateBpjsRoute
  '/api/public/v1/calculate-tax': typeof ApiPublicV1CalculateTaxRoute
  '/api/public/v1/health': typeof ApiPublicV1HealthRoute
  '/api/public/v1/openapi.json': typeof ApiPublicV1OpenapiDotjsonRoute
  '/api/public/v1/readiness': typeof ApiPublicV1ReadinessRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/api-docs': typeof ApiDocsRoute
  '/auth': typeof AuthRoute
  '/calculator': typeof CalculatorRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/audit': typeof AuthenticatedAuditRoute
  '/calendar': typeof AuthenticatedCalendarRoute
  '/contracts': typeof AuthenticatedContractsRoute
  '/country-packs': typeof AuthenticatedCountryPacksRoute
  '/dashboard': typeof AuthenticatedDashboardRoute
  '/employees': typeof AuthenticatedEmployeesRoute
  '/payroll': typeof AuthenticatedPayrollRoute
  '/platform/audit': typeof PlatformAuditRoute
  '/platform/flags': typeof PlatformFlagsRoute
  '/platform/packs': typeof PlatformPacksRoute
  '/platform/parameters': typeof PlatformParametersRoute
  '/platform/readiness': typeof PlatformReadinessRoute
  '/platform/releases': typeof PlatformReleasesRoute
  '/platform/uada': typeof PlatformUadaRoute
  '/packs': typeof PacksIndexRoute
  '/platform': typeof PlatformIndexRoute
  '/api/public/calculate-bpjs': typeof ApiPublicCalculateBpjsRoute
  '/api/public/calculate-tax': typeof ApiPublicCalculateTaxRoute
  '/api/public/openapi.json': typeof ApiPublicOpenapiDotjsonRoute
  '/api/public/v1/calculate-bpjs': typeof ApiPublicV1CalculateBpjsRoute
  '/api/public/v1/calculate-tax': typeof ApiPublicV1CalculateTaxRoute
  '/api/public/v1/health': typeof ApiPublicV1HealthRoute
  '/api/public/v1/openapi.json': typeof ApiPublicV1OpenapiDotjsonRoute
  '/api/public/v1/readiness': typeof ApiPublicV1ReadinessRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_authenticated': typeof AuthenticatedRouteRouteWithChildren
  '/platform': typeof PlatformRouteRouteWithChildren
  '/api-docs': typeof ApiDocsRoute
  '/auth': typeof AuthRoute
  '/calculator': typeof CalculatorRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/_authenticated/audit': typeof AuthenticatedAuditRoute
  '/_authenticated/calendar': typeof AuthenticatedCalendarRoute
  '/_authenticated/contracts': typeof AuthenticatedContractsRoute
  '/_authenticated/country-packs': typeof AuthenticatedCountryPacksRoute
  '/_authenticated/dashboard': typeof AuthenticatedDashboardRoute
  '/_authenticated/employees': typeof AuthenticatedEmployeesRoute
  '/_authenticated/payroll': typeof AuthenticatedPayrollRoute
  '/platform/audit': typeof PlatformAuditRoute
  '/platform/flags': typeof PlatformFlagsRoute
  '/platform/packs': typeof PlatformPacksRoute
  '/platform/parameters': typeof PlatformParametersRoute
  '/platform/readiness': typeof PlatformReadinessRoute
  '/platform/releases': typeof PlatformReleasesRoute
  '/platform/uada': typeof PlatformUadaRoute
  '/packs/': typeof PacksIndexRoute
  '/platform/': typeof PlatformIndexRoute
  '/api/public/calculate-bpjs': typeof ApiPublicCalculateBpjsRoute
  '/api/public/calculate-tax': typeof ApiPublicCalculateTaxRoute
  '/api/public/openapi.json': typeof ApiPublicOpenapiDotjsonRoute
  '/api/public/v1/calculate-bpjs': typeof ApiPublicV1CalculateBpjsRoute
  '/api/public/v1/calculate-tax': typeof ApiPublicV1CalculateTaxRoute
  '/api/public/v1/health': typeof ApiPublicV1HealthRoute
  '/api/public/v1/openapi.json': typeof ApiPublicV1OpenapiDotjsonRoute
  '/api/public/v1/readiness': typeof ApiPublicV1ReadinessRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/platform'
    | '/api-docs'
    | '/auth'
    | '/calculator'
    | '/sitemap.xml'
    | '/audit'
    | '/calendar'
    | '/contracts'
    | '/country-packs'
    | '/dashboard'
    | '/employees'
    | '/payroll'
    | '/platform/audit'
    | '/platform/flags'
    | '/platform/packs'
    | '/platform/parameters'
    | '/platform/readiness'
    | '/platform/releases'
    | '/platform/uada'
    | '/packs/'
    | '/platform/'
    | '/api/public/calculate-bpjs'
    | '/api/public/calculate-tax'
    | '/api/public/openapi.json'
    | '/api/public/v1/calculate-bpjs'
    | '/api/public/v1/calculate-tax'
    | '/api/public/v1/health'
    | '/api/public/v1/openapi.json'
    | '/api/public/v1/readiness'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/api-docs'
    | '/auth'
    | '/calculator'
    | '/sitemap.xml'
    | '/audit'
    | '/calendar'
    | '/contracts'
    | '/country-packs'
    | '/dashboard'
    | '/employees'
    | '/payroll'
    | '/platform/audit'
    | '/platform/flags'
    | '/platform/packs'
    | '/platform/parameters'
    | '/platform/readiness'
    | '/platform/releases'
    | '/platform/uada'
    | '/packs'
    | '/platform'
    | '/api/public/calculate-bpjs'
    | '/api/public/calculate-tax'
    | '/api/public/openapi.json'
    | '/api/public/v1/calculate-bpjs'
    | '/api/public/v1/calculate-tax'
    | '/api/public/v1/health'
    | '/api/public/v1/openapi.json'
    | '/api/public/v1/readiness'
  id:
    | '__root__'
    | '/'
    | '/_authenticated'
    | '/platform'
    | '/api-docs'
    | '/auth'
    | '/calculator'
    | '/sitemap.xml'
    | '/_authenticated/audit'
    | '/_authenticated/calendar'
    | '/_authenticated/contracts'
    | '/_authenticated/country-packs'
    | '/_authenticated/dashboard'
    | '/_authenticated/employees'
    | '/_authenticated/payroll'
    | '/platform/audit'
    | '/platform/flags'
    | '/platform/packs'
    | '/platform/parameters'
    | '/platform/readiness'
    | '/platform/releases'
    | '/platform/uada'
    | '/packs/'
    | '/platform/'
    | '/api/public/calculate-bpjs'
    | '/api/public/calculate-tax'
    | '/api/public/openapi.json'
    | '/api/public/v1/calculate-bpjs'
    | '/api/public/v1/calculate-tax'
    | '/api/public/v1/health'
    | '/api/public/v1/openapi.json'
    | '/api/public/v1/readiness'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AuthenticatedRouteRoute: typeof AuthenticatedRouteRouteWithChildren
  PlatformRouteRoute: typeof PlatformRouteRouteWithChildren
  ApiDocsRoute: typeof ApiDocsRoute
  AuthRoute: typeof AuthRoute
  CalculatorRoute: typeof CalculatorRoute
  SitemapDotxmlRoute: typeof SitemapDotxmlRoute
  PacksIndexRoute: typeof PacksIndexRoute
  ApiPublicCalculateBpjsRoute: typeof ApiPublicCalculateBpjsRoute
  ApiPublicCalculateTaxRoute: typeof ApiPublicCalculateTaxRoute
  ApiPublicOpenapiDotjsonRoute: typeof ApiPublicOpenapiDotjsonRoute
  ApiPublicV1CalculateBpjsRoute: typeof ApiPublicV1CalculateBpjsRoute
  ApiPublicV1CalculateTaxRoute: typeof ApiPublicV1CalculateTaxRoute
  ApiPublicV1HealthRoute: typeof ApiPublicV1HealthRoute
  ApiPublicV1OpenapiDotjsonRoute: typeof ApiPublicV1OpenapiDotjsonRoute
  ApiPublicV1ReadinessRoute: typeof ApiPublicV1ReadinessRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/sitemap.xml': {
      id: '/sitemap.xml'
      path: '/sitemap.xml'
      fullPath: '/sitemap.xml'
      preLoaderRoute: typeof SitemapDotxmlRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/calculator': {
      id: '/calculator'
      path: '/calculator'
      fullPath: '/calculator'
      preLoaderRoute: typeof CalculatorRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth': {
      id: '/auth'
      path: '/auth'
      fullPath: '/auth'
      preLoaderRoute: typeof AuthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api-docs': {
      id: '/api-docs'
      path: '/api-docs'
      fullPath: '/api-docs'
      preLoaderRoute: typeof ApiDocsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/platform': {
      id: '/platform'
      path: '/platform'
      fullPath: '/platform'
      preLoaderRoute: typeof PlatformRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated': {
      id: '/_authenticated'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AuthenticatedRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/platform/': {
      id: '/platform/'
      path: '/'
      fullPath: '/platform/'
      preLoaderRoute: typeof PlatformIndexRouteImport
      parentRoute: typeof PlatformRouteRoute
    }
    '/packs/': {
      id: '/packs/'
      path: '/packs'
      fullPath: '/packs/'
      preLoaderRoute: typeof PacksIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/platform/uada': {
      id: '/platform/uada'
      path: '/uada'
      fullPath: '/platform/uada'
      preLoaderRoute: typeof PlatformUadaRouteImport
      parentRoute: typeof PlatformRouteRoute
    }
    '/platform/releases': {
      id: '/platform/releases'
      path: '/releases'
      fullPath: '/platform/releases'
      preLoaderRoute: typeof PlatformReleasesRouteImport
      parentRoute: typeof PlatformRouteRoute
    }
    '/platform/readiness': {
      id: '/platform/readiness'
      path: '/readiness'
      fullPath: '/platform/readiness'
      preLoaderRoute: typeof PlatformReadinessRouteImport
      parentRoute: typeof PlatformRouteRoute
    }
    '/platform/parameters': {
      id: '/platform/parameters'
      path: '/parameters'
      fullPath: '/platform/parameters'
      preLoaderRoute: typeof PlatformParametersRouteImport
      parentRoute: typeof PlatformRouteRoute
    }
    '/platform/packs': {
      id: '/platform/packs'
      path: '/packs'
      fullPath: '/platform/packs'
      preLoaderRoute: typeof PlatformPacksRouteImport
      parentRoute: typeof PlatformRouteRoute
    }
    '/platform/flags': {
      id: '/platform/flags'
      path: '/flags'
      fullPath: '/platform/flags'
      preLoaderRoute: typeof PlatformFlagsRouteImport
      parentRoute: typeof PlatformRouteRoute
    }
    '/platform/audit': {
      id: '/platform/audit'
      path: '/audit'
      fullPath: '/platform/audit'
      preLoaderRoute: typeof PlatformAuditRouteImport
      parentRoute: typeof PlatformRouteRoute
    }
    '/_authenticated/payroll': {
      id: '/_authenticated/payroll'
      path: '/payroll'
      fullPath: '/payroll'
      preLoaderRoute: typeof AuthenticatedPayrollRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/employees': {
      id: '/_authenticated/employees'
      path: '/employees'
      fullPath: '/employees'
      preLoaderRoute: typeof AuthenticatedEmployeesRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/dashboard': {
      id: '/_authenticated/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof AuthenticatedDashboardRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/country-packs': {
      id: '/_authenticated/country-packs'
      path: '/country-packs'
      fullPath: '/country-packs'
      preLoaderRoute: typeof AuthenticatedCountryPacksRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/contracts': {
      id: '/_authenticated/contracts'
      path: '/contracts'
      fullPath: '/contracts'
      preLoaderRoute: typeof AuthenticatedContractsRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/calendar': {
      id: '/_authenticated/calendar'
      path: '/calendar'
      fullPath: '/calendar'
      preLoaderRoute: typeof AuthenticatedCalendarRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/audit': {
      id: '/_authenticated/audit'
      path: '/audit'
      fullPath: '/audit'
      preLoaderRoute: typeof AuthenticatedAuditRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/api/public/openapi.json': {
      id: '/api/public/openapi.json'
      path: '/api/public/openapi.json'
      fullPath: '/api/public/openapi.json'
      preLoaderRoute: typeof ApiPublicOpenapiDotjsonRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/calculate-tax': {
      id: '/api/public/calculate-tax'
      path: '/api/public/calculate-tax'
      fullPath: '/api/public/calculate-tax'
      preLoaderRoute: typeof ApiPublicCalculateTaxRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/calculate-bpjs': {
      id: '/api/public/calculate-bpjs'
      path: '/api/public/calculate-bpjs'
      fullPath: '/api/public/calculate-bpjs'
      preLoaderRoute: typeof ApiPublicCalculateBpjsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/v1/readiness': {
      id: '/api/public/v1/readiness'
      path: '/api/public/v1/readiness'
      fullPath: '/api/public/v1/readiness'
      preLoaderRoute: typeof ApiPublicV1ReadinessRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/v1/openapi.json': {
      id: '/api/public/v1/openapi.json'
      path: '/api/public/v1/openapi.json'
      fullPath: '/api/public/v1/openapi.json'
      preLoaderRoute: typeof ApiPublicV1OpenapiDotjsonRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/v1/health': {
      id: '/api/public/v1/health'
      path: '/api/public/v1/health'
      fullPath: '/api/public/v1/health'
      preLoaderRoute: typeof ApiPublicV1HealthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/v1/calculate-tax': {
      id: '/api/public/v1/calculate-tax'
      path: '/api/public/v1/calculate-tax'
      fullPath: '/api/public/v1/calculate-tax'
      preLoaderRoute: typeof ApiPublicV1CalculateTaxRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/v1/calculate-bpjs': {
      id: '/api/public/v1/calculate-bpjs'
      path: '/api/public/v1/calculate-bpjs'
      fullPath: '/api/public/v1/calculate-bpjs'
      preLoaderRoute: typeof ApiPublicV1CalculateBpjsRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

interface AuthenticatedRouteRouteChildren {
  AuthenticatedAuditRoute: typeof AuthenticatedAuditRoute
  AuthenticatedCalendarRoute: typeof AuthenticatedCalendarRoute
  AuthenticatedContractsRoute: typeof AuthenticatedContractsRoute
  AuthenticatedCountryPacksRoute: typeof AuthenticatedCountryPacksRoute
  AuthenticatedDashboardRoute: typeof AuthenticatedDashboardRoute
  AuthenticatedEmployeesRoute: typeof AuthenticatedEmployeesRoute
  AuthenticatedPayrollRoute: typeof AuthenticatedPayrollRoute
}

const AuthenticatedRouteRouteChildren: AuthenticatedRouteRouteChildren = {
  AuthenticatedAuditRoute: AuthenticatedAuditRoute,
  AuthenticatedCalendarRoute: AuthenticatedCalendarRoute,
  AuthenticatedContractsRoute: AuthenticatedContractsRoute,
  AuthenticatedCountryPacksRoute: AuthenticatedCountryPacksRoute,
  AuthenticatedDashboardRoute: AuthenticatedDashboardRoute,
  AuthenticatedEmployeesRoute: AuthenticatedEmployeesRoute,
  AuthenticatedPayrollRoute: AuthenticatedPayrollRoute,
}

const AuthenticatedRouteRouteWithChildren =
  AuthenticatedRouteRoute._addFileChildren(AuthenticatedRouteRouteChildren)

interface PlatformRouteRouteChildren {
  PlatformAuditRoute: typeof PlatformAuditRoute
  PlatformFlagsRoute: typeof PlatformFlagsRoute
  PlatformPacksRoute: typeof PlatformPacksRoute
  PlatformParametersRoute: typeof PlatformParametersRoute
  PlatformReadinessRoute: typeof PlatformReadinessRoute
  PlatformReleasesRoute: typeof PlatformReleasesRoute
  PlatformUadaRoute: typeof PlatformUadaRoute
  PlatformIndexRoute: typeof PlatformIndexRoute
}

const PlatformRouteRouteChildren: PlatformRouteRouteChildren = {
  PlatformAuditRoute: PlatformAuditRoute,
  PlatformFlagsRoute: PlatformFlagsRoute,
  PlatformPacksRoute: PlatformPacksRoute,
  PlatformParametersRoute: PlatformParametersRoute,
  PlatformReadinessRoute: PlatformReadinessRoute,
  PlatformReleasesRoute: PlatformReleasesRoute,
  PlatformUadaRoute: PlatformUadaRoute,
  PlatformIndexRoute: PlatformIndexRoute,
}

const PlatformRouteRouteWithChildren = PlatformRouteRoute._addFileChildren(
  PlatformRouteRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AuthenticatedRouteRoute: AuthenticatedRouteRouteWithChildren,
  PlatformRouteRoute: PlatformRouteRouteWithChildren,
  ApiDocsRoute: ApiDocsRoute,
  AuthRoute: AuthRoute,
  CalculatorRoute: CalculatorRoute,
  SitemapDotxmlRoute: SitemapDotxmlRoute,
  PacksIndexRoute: PacksIndexRoute,
  ApiPublicCalculateBpjsRoute: ApiPublicCalculateBpjsRoute,
  ApiPublicCalculateTaxRoute: ApiPublicCalculateTaxRoute,
  ApiPublicOpenapiDotjsonRoute: ApiPublicOpenapiDotjsonRoute,
  ApiPublicV1CalculateBpjsRoute: ApiPublicV1CalculateBpjsRoute,
  ApiPublicV1CalculateTaxRoute: ApiPublicV1CalculateTaxRoute,
  ApiPublicV1HealthRoute: ApiPublicV1HealthRoute,
  ApiPublicV1OpenapiDotjsonRoute: ApiPublicV1OpenapiDotjsonRoute,
  ApiPublicV1ReadinessRoute: ApiPublicV1ReadinessRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
